"""Rename name column to full_name

Revision ID: dfd8ae649e00
Revises: 791279dd0760
Create Date: 2024-03-18 10:47:50.660886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd8ae649e00'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_index('ix_students_name', table_name='students')
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.create_index('ix_students_name', 'students', ['name'], unique=False)
    op.drop_column('students', 'full_name')
    # ### end Alembic commands ###
